// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/repositories/model/local_models/bible/bible.dart';
import 'src/repositories/model/local_models/inductive/folder.dart';
import 'src/repositories/model/local_models/inductive/fragment.dart';
import 'src/repositories/model/local_models/inductive/word.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 8011048593561155606),
      name: 'FolderLocal',
      lastPropertyId: const obx_int.IdUid(2, 18929626888440079),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5929135141955702599),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 18929626888440079),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'fragments', srcEntity: 'FragmentLocal', srcField: 'folder')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 3960909509973879731),
      name: 'FragmentLocal',
      lastPropertyId: const obx_int.IdUid(6, 5389801780994316776),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7166941501949261613),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2218065215704425944),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4637618593733295496),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1037542684261231704),
            name: 'bookId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7548585482656102127),
            name: 'bookName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5389801780994316776),
            name: 'folderId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 5597378087385502750),
            relationTarget: 'FolderLocal')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'text', srcEntity: 'VerseLocal', srcField: 'fragment')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 1454267786881740801),
      name: 'VerseLocal',
      lastPropertyId: const obx_int.IdUid(6, 2979426491443797314),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4964970067270604321),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6275203807537770890),
            name: 'bookId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8641133270969219601),
            name: 'chapterId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8391278738909900399),
            name: 'number',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2979426491443797314),
            name: 'fragmentId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 4074713988327459675),
            relationTarget: 'FragmentLocal')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'words', srcEntity: 'WordLocal', srcField: 'verse')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 2968965411853438485),
      name: 'WordLocal',
      lastPropertyId: const obx_int.IdUid(5, 5803068062754091279),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8035096912124096853),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2827609652975143762),
            name: 'value',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5803068062754091279),
            name: 'verseId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 1691014882085764308),
            relationTarget: 'VerseLocal')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 7185371223478614403),
      name: 'BookLocal',
      lastPropertyId: const obx_int.IdUid(5, 8728132709671035824),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4991224564528957844),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1129472134480709850),
            name: 'bookId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8736782475556116186),
            name: 'translate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 659185716363673351),
            name: 'bookName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8728132709671035824),
            name: 'shortName',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 3650286781991589145),
      name: 'ChapterLocal',
      lastPropertyId: const obx_int.IdUid(3, 3737092396647499978),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3843379987178825861),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2996033745922202548),
            name: 'chapterId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3737092396647499978),
            name: 'bookId',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(5, 6780013490363375989),
            name: 'verses',
            targetId: const obx_int.IdUid(3, 1454267786881740801))
      ],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(6, 3650286781991589145),
      lastIndexId: const obx_int.IdUid(5, 1691014882085764308),
      lastRelationId: const obx_int.IdUid(5, 6780013490363375989),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [4649469458336730149, 1373592188249137506],
      retiredPropertyUids: const [
        3859540035582067240,
        4519813948655732556,
        9102258010613119613
      ],
      retiredRelationUids: const [
        6968967606021430674,
        903052182966308622,
        4276822390928392685,
        2306486577618217812
      ],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    FolderLocal: obx_int.EntityDefinition<FolderLocal>(
        model: _entities[0],
        toOneRelations: (FolderLocal object) => [],
        toManyRelations: (FolderLocal object) => {
              obx_int.RelInfo<FragmentLocal>.toOneBacklink(6, object.id,
                      (FragmentLocal srcObject) => srcObject.folder):
                  object.fragments
            },
        getId: (FolderLocal object) => object.id,
        setId: (FolderLocal object, int id) {
          object.id = id;
        },
        objectToFB: (FolderLocal object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = FolderLocal(id: idParam, name: nameParam);
          obx_int.InternalToManyAccess.setRelInfo<FolderLocal>(
              object.fragments,
              store,
              obx_int.RelInfo<FragmentLocal>.toOneBacklink(
                  6, object.id, (FragmentLocal srcObject) => srcObject.folder));
          return object;
        }),
    FragmentLocal: obx_int.EntityDefinition<FragmentLocal>(
        model: _entities[1],
        toOneRelations: (FragmentLocal object) => [object.folder],
        toManyRelations: (FragmentLocal object) => {
              obx_int.RelInfo<VerseLocal>.toOneBacklink(6, object.id,
                  (VerseLocal srcObject) => srcObject.fragment): object.text
            },
        getId: (FragmentLocal object) => object.id,
        setId: (FragmentLocal object, int id) {
          object.id = id;
        },
        objectToFB: (FragmentLocal object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final descriptionOffset = fbb.writeString(object.description);
          final bookNameOffset = fbb.writeString(object.bookName);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addInt64(3, object.bookId);
          fbb.addOffset(4, bookNameOffset);
          fbb.addInt64(5, object.folder.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final bookIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final bookNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final object = FragmentLocal(
              id: idParam,
              name: nameParam,
              description: descriptionParam,
              bookId: bookIdParam,
              bookName: bookNameParam);
          object.folder.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.folder.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<FragmentLocal>(
              object.text,
              store,
              obx_int.RelInfo<VerseLocal>.toOneBacklink(
                  6, object.id, (VerseLocal srcObject) => srcObject.fragment));
          return object;
        }),
    VerseLocal: obx_int.EntityDefinition<VerseLocal>(
        model: _entities[2],
        toOneRelations: (VerseLocal object) => [object.fragment],
        toManyRelations: (VerseLocal object) => {
              obx_int.RelInfo<WordLocal>.toOneBacklink(
                      5, object.id, (WordLocal srcObject) => srcObject.verse):
                  object.words
            },
        getId: (VerseLocal object) => object.id,
        setId: (VerseLocal object, int id) {
          object.id = id;
        },
        objectToFB: (VerseLocal object, fb.Builder fbb) {
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.bookId);
          fbb.addInt64(2, object.chapterId);
          fbb.addInt64(4, object.number);
          fbb.addInt64(5, object.fragment.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final numberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final bookIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final chapterIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final object = VerseLocal(
              id: idParam,
              number: numberParam,
              bookId: bookIdParam,
              chapterId: chapterIdParam);
          object.fragment.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.fragment.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<VerseLocal>(
              object.words,
              store,
              obx_int.RelInfo<WordLocal>.toOneBacklink(
                  5, object.id, (WordLocal srcObject) => srcObject.verse));
          return object;
        }),
    WordLocal: obx_int.EntityDefinition<WordLocal>(
        model: _entities[3],
        toOneRelations: (WordLocal object) => [object.verse],
        toManyRelations: (WordLocal object) => {},
        getId: (WordLocal object) => object.id,
        setId: (WordLocal object, int id) {
          object.id = id;
        },
        objectToFB: (WordLocal object, fb.Builder fbb) {
          final valueOffset = fbb.writeString(object.value);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, valueOffset);
          fbb.addInt64(4, object.verse.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final valueParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = WordLocal(id: idParam, value: valueParam);
          object.verse.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.verse.attach(store);
          return object;
        }),
    BookLocal: obx_int.EntityDefinition<BookLocal>(
        model: _entities[4],
        toOneRelations: (BookLocal object) => [],
        toManyRelations: (BookLocal object) => {},
        getId: (BookLocal object) => object.id,
        setId: (BookLocal object, int id) {
          object.id = id;
        },
        objectToFB: (BookLocal object, fb.Builder fbb) {
          final translateOffset = fbb.writeString(object.translate);
          final bookNameOffset = fbb.writeString(object.bookName);
          final shortNameOffset = fbb.writeString(object.shortName);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.bookId);
          fbb.addOffset(2, translateOffset);
          fbb.addOffset(3, bookNameOffset);
          fbb.addOffset(4, shortNameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final translateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final bookIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final bookNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final shortNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final object = BookLocal(
              id: idParam,
              translate: translateParam,
              bookId: bookIdParam,
              bookName: bookNameParam,
              shortName: shortNameParam);

          return object;
        }),
    ChapterLocal: obx_int.EntityDefinition<ChapterLocal>(
        model: _entities[5],
        toOneRelations: (ChapterLocal object) => [],
        toManyRelations: (ChapterLocal object) =>
            {obx_int.RelInfo<ChapterLocal>.toMany(5, object.id): object.verses},
        getId: (ChapterLocal object) => object.id,
        setId: (ChapterLocal object, int id) {
          object.id = id;
        },
        objectToFB: (ChapterLocal object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.chapterId);
          fbb.addInt64(2, object.bookId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final chapterIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final bookIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final object = ChapterLocal(
              id: idParam, chapterId: chapterIdParam, bookId: bookIdParam);
          obx_int.InternalToManyAccess.setRelInfo<ChapterLocal>(object.verses,
              store, obx_int.RelInfo<ChapterLocal>.toMany(5, object.id));
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FolderLocal] entity fields to define ObjectBox queries.
class FolderLocal_ {
  /// See [FolderLocal.id].
  static final id =
      obx.QueryIntegerProperty<FolderLocal>(_entities[0].properties[0]);

  /// See [FolderLocal.name].
  static final name =
      obx.QueryStringProperty<FolderLocal>(_entities[0].properties[1]);

  /// see [FolderLocal.fragments]
  static final fragments = obx.QueryBacklinkToMany<FragmentLocal, FolderLocal>(
      FragmentLocal_.folder);
}

/// [FragmentLocal] entity fields to define ObjectBox queries.
class FragmentLocal_ {
  /// See [FragmentLocal.id].
  static final id =
      obx.QueryIntegerProperty<FragmentLocal>(_entities[1].properties[0]);

  /// See [FragmentLocal.name].
  static final name =
      obx.QueryStringProperty<FragmentLocal>(_entities[1].properties[1]);

  /// See [FragmentLocal.description].
  static final description =
      obx.QueryStringProperty<FragmentLocal>(_entities[1].properties[2]);

  /// See [FragmentLocal.bookId].
  static final bookId =
      obx.QueryIntegerProperty<FragmentLocal>(_entities[1].properties[3]);

  /// See [FragmentLocal.bookName].
  static final bookName =
      obx.QueryStringProperty<FragmentLocal>(_entities[1].properties[4]);

  /// See [FragmentLocal.folder].
  static final folder = obx.QueryRelationToOne<FragmentLocal, FolderLocal>(
      _entities[1].properties[5]);

  /// see [FragmentLocal.text]
  static final text =
      obx.QueryBacklinkToMany<VerseLocal, FragmentLocal>(VerseLocal_.fragment);
}

/// [VerseLocal] entity fields to define ObjectBox queries.
class VerseLocal_ {
  /// See [VerseLocal.id].
  static final id =
      obx.QueryIntegerProperty<VerseLocal>(_entities[2].properties[0]);

  /// See [VerseLocal.bookId].
  static final bookId =
      obx.QueryIntegerProperty<VerseLocal>(_entities[2].properties[1]);

  /// See [VerseLocal.chapterId].
  static final chapterId =
      obx.QueryIntegerProperty<VerseLocal>(_entities[2].properties[2]);

  /// See [VerseLocal.number].
  static final number =
      obx.QueryIntegerProperty<VerseLocal>(_entities[2].properties[3]);

  /// See [VerseLocal.fragment].
  static final fragment = obx.QueryRelationToOne<VerseLocal, FragmentLocal>(
      _entities[2].properties[4]);

  /// see [VerseLocal.words]
  static final words =
      obx.QueryBacklinkToMany<WordLocal, VerseLocal>(WordLocal_.verse);
}

/// [WordLocal] entity fields to define ObjectBox queries.
class WordLocal_ {
  /// See [WordLocal.id].
  static final id =
      obx.QueryIntegerProperty<WordLocal>(_entities[3].properties[0]);

  /// See [WordLocal.value].
  static final value =
      obx.QueryStringProperty<WordLocal>(_entities[3].properties[1]);

  /// See [WordLocal.verse].
  static final verse =
      obx.QueryRelationToOne<WordLocal, VerseLocal>(_entities[3].properties[2]);
}

/// [BookLocal] entity fields to define ObjectBox queries.
class BookLocal_ {
  /// See [BookLocal.id].
  static final id =
      obx.QueryIntegerProperty<BookLocal>(_entities[4].properties[0]);

  /// See [BookLocal.bookId].
  static final bookId =
      obx.QueryIntegerProperty<BookLocal>(_entities[4].properties[1]);

  /// See [BookLocal.translate].
  static final translate =
      obx.QueryStringProperty<BookLocal>(_entities[4].properties[2]);

  /// See [BookLocal.bookName].
  static final bookName =
      obx.QueryStringProperty<BookLocal>(_entities[4].properties[3]);

  /// See [BookLocal.shortName].
  static final shortName =
      obx.QueryStringProperty<BookLocal>(_entities[4].properties[4]);
}

/// [ChapterLocal] entity fields to define ObjectBox queries.
class ChapterLocal_ {
  /// See [ChapterLocal.id].
  static final id =
      obx.QueryIntegerProperty<ChapterLocal>(_entities[5].properties[0]);

  /// See [ChapterLocal.chapterId].
  static final chapterId =
      obx.QueryIntegerProperty<ChapterLocal>(_entities[5].properties[1]);

  /// See [ChapterLocal.bookId].
  static final bookId =
      obx.QueryIntegerProperty<ChapterLocal>(_entities[5].properties[2]);

  /// see [ChapterLocal.verses]
  static final verses = obx.QueryRelationToMany<ChapterLocal, VerseLocal>(
      _entities[5].relations[0]);
}
