// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/repositories/model/local_models/bible/bible.dart';
import 'src/repositories/model/local_models/inductive/folder.dart';
import 'src/repositories/model/local_models/inductive/fragment.dart';
import 'src/repositories/model/local_models/inductive/word.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2354704808836906264),
      name: 'FolderLocal',
      lastPropertyId: const obx_int.IdUid(2, 7964111414782150076),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4142557069072229393),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7964111414782150076),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'fragments', srcEntity: 'FragmentLocal', srcField: 'folder')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 8864542356979381165),
      name: 'FragmentLocal',
      lastPropertyId: const obx_int.IdUid(6, 6828844625469242700),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4966738114109466114),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8164982933155899417),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4358123042564763919),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4236731623833230986),
            name: 'bookId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1247646740754642045),
            name: 'bookName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6828844625469242700),
            name: 'folderId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 6286170932481431751),
            relationTarget: 'FolderLocal')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'text', srcEntity: 'VerseLocal', srcField: 'fragment')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 7658541836684713826),
      name: 'VerseLocal',
      lastPropertyId: const obx_int.IdUid(5, 5879873086898957401),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2378728768379147097),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8053772381277776352),
            name: 'number',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3649448812682242186),
            name: 'bookId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6107660225857527849),
            name: 'chapterId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5879873086898957401),
            name: 'fragmentId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 481913656593467680),
            relationTarget: 'FragmentLocal')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'words', srcEntity: 'WordLocal', srcField: 'verse')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 3095107107054516958),
      name: 'WordLocal',
      lastPropertyId: const obx_int.IdUid(4, 5332258311812615035),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2023895090272783721),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1466011949069712379),
            name: 'value',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 943754159878733605),
            name: 'verseId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 4626927757986903153),
            relationTarget: 'VerseLocal'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5332258311812615035),
            name: 'fragmentId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 3649836660616419947),
            relationTarget: 'FragmentLocal')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(4, 3095107107054516958),
      lastIndexId: const obx_int.IdUid(4, 3649836660616419947),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    FolderLocal: obx_int.EntityDefinition<FolderLocal>(
        model: _entities[0],
        toOneRelations: (FolderLocal object) => [],
        toManyRelations: (FolderLocal object) => {
              obx_int.RelInfo<FragmentLocal>.toOneBacklink(6, object.id,
                      (FragmentLocal srcObject) => srcObject.folder):
                  object.fragments
            },
        getId: (FolderLocal object) => object.id,
        setId: (FolderLocal object, int id) {
          object.id = id;
        },
        objectToFB: (FolderLocal object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = FolderLocal(id: idParam, name: nameParam);
          obx_int.InternalToManyAccess.setRelInfo<FolderLocal>(
              object.fragments,
              store,
              obx_int.RelInfo<FragmentLocal>.toOneBacklink(
                  6, object.id, (FragmentLocal srcObject) => srcObject.folder));
          return object;
        }),
    FragmentLocal: obx_int.EntityDefinition<FragmentLocal>(
        model: _entities[1],
        toOneRelations: (FragmentLocal object) => [object.folder],
        toManyRelations: (FragmentLocal object) => {
              obx_int.RelInfo<VerseLocal>.toOneBacklink(5, object.id,
                  (VerseLocal srcObject) => srcObject.fragment): object.text
            },
        getId: (FragmentLocal object) => object.id,
        setId: (FragmentLocal object, int id) {
          object.id = id;
        },
        objectToFB: (FragmentLocal object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final descriptionOffset = fbb.writeString(object.description);
          final bookNameOffset = fbb.writeString(object.bookName);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addInt64(3, object.bookId);
          fbb.addOffset(4, bookNameOffset);
          fbb.addInt64(5, object.folder.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final bookIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final bookNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final object = FragmentLocal(
              id: idParam,
              name: nameParam,
              description: descriptionParam,
              bookId: bookIdParam,
              bookName: bookNameParam);
          object.folder.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.folder.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<FragmentLocal>(
              object.text,
              store,
              obx_int.RelInfo<VerseLocal>.toOneBacklink(
                  5, object.id, (VerseLocal srcObject) => srcObject.fragment));
          return object;
        }),
    VerseLocal: obx_int.EntityDefinition<VerseLocal>(
        model: _entities[2],
        toOneRelations: (VerseLocal object) => [object.fragment],
        toManyRelations: (VerseLocal object) => {
              obx_int.RelInfo<WordLocal>.toOneBacklink(
                      3, object.id, (WordLocal srcObject) => srcObject.verse):
                  object.words
            },
        getId: (VerseLocal object) => object.id,
        setId: (VerseLocal object, int id) {
          object.id = id;
        },
        objectToFB: (VerseLocal object, fb.Builder fbb) {
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.number);
          fbb.addInt64(2, object.bookId);
          fbb.addInt64(3, object.chapterId);
          fbb.addInt64(4, object.fragment.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final numberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final bookIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final chapterIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = VerseLocal(
              id: idParam,
              number: numberParam,
              bookId: bookIdParam,
              chapterId: chapterIdParam);
          object.fragment.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.fragment.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<VerseLocal>(
              object.words,
              store,
              obx_int.RelInfo<WordLocal>.toOneBacklink(
                  3, object.id, (WordLocal srcObject) => srcObject.verse));
          return object;
        }),
    WordLocal: obx_int.EntityDefinition<WordLocal>(
        model: _entities[3],
        toOneRelations: (WordLocal object) => [object.verse, object.fragment],
        toManyRelations: (WordLocal object) => {},
        getId: (WordLocal object) => object.id,
        setId: (WordLocal object, int id) {
          object.id = id;
        },
        objectToFB: (WordLocal object, fb.Builder fbb) {
          final valueOffset = fbb.writeString(object.value);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, valueOffset);
          fbb.addInt64(2, object.verse.targetId);
          fbb.addInt64(3, object.fragment.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final valueParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = WordLocal(id: idParam, value: valueParam);
          object.verse.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.verse.attach(store);
          object.fragment.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.fragment.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FolderLocal] entity fields to define ObjectBox queries.
class FolderLocal_ {
  /// See [FolderLocal.id].
  static final id =
      obx.QueryIntegerProperty<FolderLocal>(_entities[0].properties[0]);

  /// See [FolderLocal.name].
  static final name =
      obx.QueryStringProperty<FolderLocal>(_entities[0].properties[1]);

  /// see [FolderLocal.fragments]
  static final fragments = obx.QueryBacklinkToMany<FragmentLocal, FolderLocal>(
      FragmentLocal_.folder);
}

/// [FragmentLocal] entity fields to define ObjectBox queries.
class FragmentLocal_ {
  /// See [FragmentLocal.id].
  static final id =
      obx.QueryIntegerProperty<FragmentLocal>(_entities[1].properties[0]);

  /// See [FragmentLocal.name].
  static final name =
      obx.QueryStringProperty<FragmentLocal>(_entities[1].properties[1]);

  /// See [FragmentLocal.description].
  static final description =
      obx.QueryStringProperty<FragmentLocal>(_entities[1].properties[2]);

  /// See [FragmentLocal.bookId].
  static final bookId =
      obx.QueryIntegerProperty<FragmentLocal>(_entities[1].properties[3]);

  /// See [FragmentLocal.bookName].
  static final bookName =
      obx.QueryStringProperty<FragmentLocal>(_entities[1].properties[4]);

  /// See [FragmentLocal.folder].
  static final folder = obx.QueryRelationToOne<FragmentLocal, FolderLocal>(
      _entities[1].properties[5]);

  /// see [FragmentLocal.text]
  static final text =
      obx.QueryBacklinkToMany<VerseLocal, FragmentLocal>(VerseLocal_.fragment);
}

/// [VerseLocal] entity fields to define ObjectBox queries.
class VerseLocal_ {
  /// See [VerseLocal.id].
  static final id =
      obx.QueryIntegerProperty<VerseLocal>(_entities[2].properties[0]);

  /// See [VerseLocal.number].
  static final number =
      obx.QueryIntegerProperty<VerseLocal>(_entities[2].properties[1]);

  /// See [VerseLocal.bookId].
  static final bookId =
      obx.QueryIntegerProperty<VerseLocal>(_entities[2].properties[2]);

  /// See [VerseLocal.chapterId].
  static final chapterId =
      obx.QueryIntegerProperty<VerseLocal>(_entities[2].properties[3]);

  /// See [VerseLocal.fragment].
  static final fragment = obx.QueryRelationToOne<VerseLocal, FragmentLocal>(
      _entities[2].properties[4]);

  /// see [VerseLocal.words]
  static final words =
      obx.QueryBacklinkToMany<WordLocal, VerseLocal>(WordLocal_.verse);
}

/// [WordLocal] entity fields to define ObjectBox queries.
class WordLocal_ {
  /// See [WordLocal.id].
  static final id =
      obx.QueryIntegerProperty<WordLocal>(_entities[3].properties[0]);

  /// See [WordLocal.value].
  static final value =
      obx.QueryStringProperty<WordLocal>(_entities[3].properties[1]);

  /// See [WordLocal.verse].
  static final verse =
      obx.QueryRelationToOne<WordLocal, VerseLocal>(_entities[3].properties[2]);

  /// See [WordLocal.fragment].
  static final fragment = obx.QueryRelationToOne<WordLocal, FragmentLocal>(
      _entities[3].properties[3]);
}
