import os
import re

COLORS_INPUT = "lib/resources/inputs_files/color_ui_themes.txt"
COLOR_OUTPUT = "lib/resources/color_ui_themes.dart"
UI_THEMES_FILE = "lib/resources/ui_themes.dart"


def parse_colors(file_path):
    sections = {"light": {}, "dark": {}}
    comments = {"light": {}, "dark": {}}
    current_mode = None
    current_comment = None

    if not os.path.exists(file_path):
        print(f"File {file_path} not found.")
        return sections, comments

    with open(file_path, "r") as file:
        lines = file.readlines()
        for line in lines:
            line = line.strip()
            if not line:
                continue
            if line.startswith("#"):  # This is a comment
                current_comment = line[1:].strip()
                continue
            if line == "[LightModeColors]":
                current_mode = "light"
                current_comment = None
                continue
            if line == "[DarkModeColors]":
                current_mode = "dark"
                current_comment = None
                continue
            if ":" in line and current_mode:
                name, code = map(str.strip, line.split(":"))
                sections[current_mode][name] = code
                if current_comment:
                    comments[current_mode][name] = current_comment
                    current_comment = None

    return sections, comments

# Generate ColorsUIThemes
def generate_colors_ui_themes(sections, comments, output_path):
    with open(output_path, "w") as file:
        file.write("// AUTO-GENERATED FILE. DO NOT EDIT.\n")
        file.write("import 'package:flutter/material.dart';\n\n")
        file.write("class ColorsUIThemes {\n")
        file.write("  static final ColorsUIThemes instance = ColorsUIThemes._();\n\n")
        file.write("  ColorsUIThemes._();\n\n")
        file.write("  final _LightModeColors light = _LightModeColors();\n")
        file.write("  final _DarkModeColors dark = _DarkModeColors();\n")
        file.write("}\n\n")

        # Light mode colors
        file.write("class _LightModeColors {\n")
        for name, code in sections["light"].items():
            if name in comments["light"]:
                file.write(f"  // {comments['light'][name]}\n")
            file.write(f"  final Color {name} = Color(0xFF{code.replace('#', '')});\n")
        file.write("}\n\n")

        # Dark mode colors
        file.write("class _DarkModeColors {\n")
        for name, code in sections["dark"].items():
            if name in comments["dark"]:
                file.write(f"  // {comments['dark'][name]}\n")
            file.write(f"  final Color {name} = Color(0xFF{code.replace('#', '')});\n")
        file.write("}\n")
    print(f"File {output_path} successfully generated.")

# Generate getters for UIThemes
def generate_color_getters(sections, comments):
    getters = []
    for color in sections["light"]:
        comment = comments["light"].get(color, "")
        if comment:
            getters.append(f"  // {comment}")
        getter = f"  Color get {color} =>\n      isDarkTheme ? ColorsUIThemes.instance.dark.{color} : ColorsUIThemes.instance.light.{color};"
        getters.append(getter)
    return "\n\n".join(getters)

# Update UIThemes.dart
def update_ui_themes_file(getters, file_path):
    if not os.path.exists(file_path):
        print(f"File {file_path} not found.")
        return

    with open(file_path, "r") as file:
        content = file.read()

    # Remove old generated getters
    content = re.sub(
        r"// Automatically generated getters for colors.*?// End of autogenerated getters",
        "",
        content,
        flags=re.S,
    )

    # Insert new getters
    insertion_point = content.rfind("}")
    new_content = (
        content[:insertion_point]
        + "// Automatically generated getters for colors\n"
        + getters
        + "\n  // End of autogenerated getters\n"
        + content[insertion_point:]
    )

    with open(file_path, "w") as file:
        file.write(new_content)

    print(f"File {file_path} successfully updated.")

# Main logic
def main():
    print("File generation started...")

    # Parse colors
    sections, comments = parse_colors(COLORS_INPUT)

    # Generate ColorsUIThemes
    generate_colors_ui_themes(sections, comments, COLOR_OUTPUT)

    # Generate getters for UIThemes
    getters = generate_color_getters(sections, comments)

    # Update UIThemes.dart
    update_ui_themes_file(getters, UI_THEMES_FILE)

    print("Generation completed!")

if __name__ == "__main__":
    main()