import 'package:bible_depth/data/bible/rst.dart';
import 'package:bible_depth/models/wrap_entity.dart';
import 'package:bible_depth/models/fragment.dart';

Future<Fragment> getFragment() async {
  int bookId = 1;

  // start
  int chapterStart = 2;
  int verseStart = 1;

  // end
  int chapterEnd = 3;
  int verseEnd = 5;

  List<WrapEntity> listWrap = [];

  var translate = await Rst.instance;
  var book = translate.books[bookId - 1];
  for (var c = chapterStart - 1; c < chapterEnd; c++) {
    var vStart = c + 1 == chapterStart ? verseStart : 1;
    var vEnd = c + 1 == chapterEnd ? verseEnd : 99999999999;

    var chapter = book.chapters[c];
    for (var v = vStart - 1; (v < chapter.verses.length) && (v < vEnd); v++) {
      var verse = chapter.verses[v];

      listWrap.add(VerseIndex(value: '${chapter.id}:${verse.id}'));

      List<String> words = verse.text.split(' ');
      for (var word in words) {
        listWrap.add(Word(value: word));
        listWrap.add(Space());
      }
    }
  }

  return Fragment(
    id: 1,
    text: listWrap,
    name: translate.books[bookId - 1].bookName +
        ' $chapterStart:$verseStart-$chapterEnd:$verseEnd',
  );
  if (true) {
    return Fragment(
      id: 1,
      name: 'Евангелие от Иоанна',
      text: [
        Word(value: '1'),
        Space(),
        Word(value: 'В'),
        Space(),
        Word(value: 'начале'),
        Space(),
        Word(value: 'было'),
        Space(),
        Word(value: 'Слово,'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'Слово'),
        Space(),
        Word(value: 'было'),
        Space(),
        Word(value: 'у'),
        Space(),
        Word(value: 'Бога,'),
        Space(),
        Word(value: 'и'),
        LineBreak(),
        Space(),
        Word(value: 'Слово'),
        Space(),
        Word(value: 'было'),
        Space(),
        Word(value: 'Бог.'),
        Space(),
        Word(value: '2'),
        Space(),
        Word(value: 'Оно'),
        Space(),
        Word(value: 'было'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'начале'),
        Space(),
        Word(value: 'у'),
        Space(),
        Word(value: 'Бога.'),
        Space(),
        Word(value: '3'),
        Space(),
        Word(value: 'Все'),
        Space(),
        Word(value: 'чрез'),
        Space(),
        Word(value: 'Него'),
        Space(),
        Word(value: 'начало'),
        Space(),
        Word(value: 'быть,'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'без'),
        Space(),
        Word(value: 'Него'),
        Space(),
        Word(value: 'ничто'),
        Space(),
        Word(value: 'не'),
        Space(),
        Word(value: 'начало'),
        Space(),
        Word(value: 'быть,'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'начало'),
        Space(),
        Word(value: 'быть.'),
        Space(),
        Word(value: '4'),
        Space(),
        Word(value: 'В'),
        Space(),
        Word(value: 'Нем'),
        Space(),
        Word(value: 'была'),
        Space(),
        Word(value: 'жизнь,'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'жизнь'),
        Space(),
        Word(value: 'была'),
        Space(),
        Word(value: 'свет'),
        Space(),
        Word(value: 'человеков.'),
        Space(),
        Word(value: '5'),
        Space(),
        Word(value: 'И'),
        Space(),
        Word(value: 'свет'),
        Space(),
        Word(value: 'во'),
        Space(),
        Word(value: 'тьме'),
        Space(),
        Word(value: 'светит,'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'тьма'),
        Space(),
        Word(value: 'не'),
        Space(),
        Word(value: 'объяла'),
        Space(),
        Word(value: 'его.'),
        Space(),
        Word(value: '6'),
        Space(),
        Word(value: 'Был'),
        Space(),
        Word(value: 'человек,'),
        Space(),
        Word(value: 'посланный'),
        Space(),
        Word(value: 'от'),
        Space(),
        Word(value: 'Бога;'),
        Space(),
        Word(value: 'имя'),
        Space(),
        Word(value: 'ему'),
        Space(),
        Word(value: 'Иоанн.'),
        Space(),
        Word(value: '7'),
        Space(),
        Word(value: 'Он'),
        Space(),
        Word(value: 'пришел'),
        Space(),
        Word(value: 'для'),
        Space(),
        Word(value: 'свидетельства,'),
        Space(),
        Word(value: 'чтобы'),
        Space(),
        Word(value: 'свидетельствовать'),
        Space(),
        Word(value: 'о'),
        Space(),
        Word(value: 'Свете,'),
        Space(),
        Word(value: 'дабы'),
        Space(),
        Word(value: 'все'),
        Space(),
        Word(value: 'уверовали'),
        Space(),
        Word(value: 'чрез'),
        Space(),
        Word(value: 'него.'),
        Space(),
        Word(value: '8'),
        Space(),
        Word(value: 'Он'),
        Space(),
        Word(value: 'не'),
        Space(),
        Word(value: 'был'),
        Space(),
        Word(value: 'свет,'),
        Space(),
        Word(value: 'но'),
        Space(),
        Word(value: 'был'),
        Space(),
        Word(value: 'послан,'),
        Space(),
        Word(value: 'чтобы'),
        Space(),
        Word(value: 'свидетельствовать'),
        Space(),
        Word(value: 'о'),
        Space(),
        Word(value: 'Свете.'),
        Space(),
        Word(value: '9'),
        Space(),
        Word(value: 'Был'),
        Space(),
        Word(value: 'Свет'),
        Space(),
        Word(value: 'истинный,'),
        Space(),
        Word(value: 'Который'),
        Space(),
        Word(value: 'просвещает'),
        Space(),
        Word(value: 'всякого'),
        Space(),
        Word(value: 'человека,'),
        Space(),
        Word(value: 'приходящего'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'мир.'),
        Space(),
        Word(value: '10'),
        Space(),
        Word(value: 'В'),
        Space(),
        Word(value: 'мире'),
        Space(),
        Word(value: 'был,'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'мир'),
        Space(),
        Word(value: 'чрез'),
        Space(),
        Word(value: 'Него'),
        Space(),
        Word(value: 'начал'),
        Space(),
        Word(value: 'быть,'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'мир'),
        Space(),
        Word(value: 'Его'),
        Space(),
        Word(value: 'не'),
        Space(),
        Word(value: 'познал.'),
        Space(),
        Word(value: '11'),
        Space(),
        Word(value: 'Пришел'),
        Space(),
        Word(value: 'к'),
        Space(),
        Word(value: 'своим,'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'свои'),
        Space(),
        Word(value: 'Его'),
        Space(),
        Word(value: 'не'),
        Space(),
        Word(value: 'приняли.'),
        Space(),
        Word(value: '12'),
        Space(),
        Word(value: 'А'),
        Space(),
        Word(value: 'тем,'),
        Space(),
        Word(value: 'которые'),
        Space(),
        Word(value: 'приняли'),
        Space(),
        Word(value: 'Его,'),
        Space(),
        Word(value: 'верующим'),
        Space(),
        Word(value: 'во'),
        Space(),
        Word(value: 'имя'),
        Space(),
        Word(value: 'Его,'),
        Space(),
        Word(value: 'дал'),
        Space(),
        Word(value: 'власть'),
        Space(),
        Word(value: 'быть'),
        Space(),
        Word(value: 'чадами'),
        Space(),
        Word(value: 'Божиими,'),
        Space(),
        Word(value: '13'),
        Space(),
        Word(value: 'которые'),
        Space(),
        Word(value: 'ни'),
        Space(),
        Word(value: 'от'),
        Space(),
        Word(value: 'крови,'),
        Space(),
        Word(value: 'ни'),
        Space(),
        Word(value: 'от'),
        Space(),
        Word(value: 'хотения'),
        Space(),
        Word(value: 'плоти,'),
        Space(),
        Word(value: 'ни'),
        Space(),
        Word(value: 'от'),
        Space(),
        Word(value: 'хотения'),
        Space(),
        Word(value: 'мужа,'),
        Space(),
        Word(value: 'но'),
        Space(),
        Word(value: 'от'),
        Space(),
        Word(value: 'Бога'),
        Space(),
        Word(value: 'родились.'),
        Space(),
        Word(value: '14'),
        Space(),
        Word(value: 'И'),
        Space(),
        Word(value: 'Слово'),
        Space(),
        Word(value: 'стало'),
        Space(),
        Word(value: 'плотию'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'обитало'),
        Space(),
        Word(value: 'с'),
        Space(),
        Word(value: 'нами,'),
        Space(),
        Word(value: 'полное'),
        Space(),
        Word(value: 'благодати'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'истины;'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'мы'),
        Space(),
        Word(value: 'видели'),
        Space(),
        Word(value: 'славу'),
        Space(),
        Word(value: 'Его,'),
        Space(),
        Word(value: 'славу,'),
        Space(),
        Word(value: 'как'),
        Space(),
        Word(value: 'Единородного'),
        Space(),
        Word(value: 'от'),
        Space(),
        Word(value: 'Отца.'),
        Space(),
        Word(value: '15'),
        Space(),
        Word(value: 'Иоанн'),
        Space(),
        Word(value: 'свидетельствует'),
        Space(),
        Word(value: 'о'),
        Space(),
        Word(value: 'Нем'),
        Space(),
        Word(value: 'и,'),
        Space(),
        Word(value: 'восклицая,'),
        Space(),
        Word(value: 'говорит:'),
        Space(),
        Word(value: 'Сей'),
        Space(),
        Word(value: 'был'),
        Space(),
        Word(value: 'Тот,'),
        Space(),
        Word(value: 'о'),
        Space(),
        Word(value: 'Котором'),
        Space(),
        Word(value: 'я'),
        Space(),
        Word(value: 'сказал,'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'Идущий'),
        Space(),
        Word(value: 'за'),
        Space(),
        Word(value: 'мною'),
        Space(),
        Word(value: 'стал'),
        Space(),
        Word(value: 'впереди'),
        Space(),
        Word(value: 'меня,'),
        Space(),
        Word(value: 'потому'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'был'),
        Space(),
        Word(value: 'прежде'),
        Space(),
        Word(value: 'меня.'),
        Space(),
        Word(value: '16'),
        Space(),
        Word(value: 'И'),
        Space(),
        Word(value: 'от'),
        Space(),
        Word(value: 'полноты'),
        Space(),
        Word(value: 'Его'),
        Space(),
        Word(value: 'все'),
        Space(),
        Word(value: 'мы'),
        Space(),
        Word(value: 'приняли'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'благодать'),
        Space(),
        Word(value: 'на'),
        Space(),
        Word(value: 'благодать,'),
        Space(),
        Word(value: '17'),
        Space(),
        Word(value: 'ибо'),
        Space(),
        Word(value: 'закон'),
        Space(),
        Word(value: 'дан'),
        Space(),
        Word(value: 'чрез'),
        Space(),
        Word(value: 'Моисея;'),
        Space(),
        Word(value: 'благодать'),
        Space(),
        Word(value: 'же'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'истина'),
        Space(),
        Word(value: 'произошли'),
        Space(),
        Word(value: 'чрез'),
        Space(),
        Word(value: 'Иисуса'),
        Space(),
        Word(value: 'Христа.'),
        Space(),
        Word(value: '18'),
        Space(),
        Word(value: 'Бога'),
        Space(),
        Word(value: 'не'),
        Space(),
        Word(value: 'видел'),
        Space(),
        Word(value: 'никто'),
        Space(),
        Word(value: 'никогда;'),
        Space(),
        Word(value: 'Единородный'),
        Space(),
        Word(value: 'Сын,'),
        Space(),
        Word(value: 'сущий'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'недре'),
        Space(),
        Word(value: 'Отчем,'),
        Space(),
        Word(value: 'Он'),
        Space(),
        Word(value: 'явил.'),
        Space(),
        Word(value: '19'),
        Space(),
        Word(value: 'И'),
        Space(),
        Word(value: 'вот'),
        Space(),
        Word(value: 'свидетельство'),
        Space(),
        Word(value: 'Иоанна,'),
        Space(),
        Word(value: 'когда'),
        Space(),
        Word(value: 'Иудеи'),
        Space(),
        Word(value: 'прислали'),
        Space(),
        Word(value: 'из'),
        Space(),
        Word(value: 'Иерусалима'),
        Space(),
        Word(value: 'священников'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'левитов'),
        Space(),
        Word(value: 'спросить'),
        Space(),
        Word(value: 'его:'),
        Space(),
        Word(value: 'кто'),
        Space(),
        Word(value: 'ты?'),
        Space(),
        Word(value: '20'),
        Space(),
        Word(value: 'Он'),
        Space(),
        Word(value: 'объявил,'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'не'),
        Space(),
        Word(value: 'отрекся,'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'объявил,'),
        Space(),
        Word(value: 'что:'),
        Space(),
        Word(value: 'я'),
        Space(),
        Word(value: 'не'),
        Space(),
        Word(value: 'Христос.'),
        Space(),
        Word(value: '21'),
        Space(),
        Word(value: 'И'),
        Space(),
        Word(value: 'спросили'),
        Space(),
        Word(value: 'его:'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'же?'),
        Space(),
        Word(value: 'ты'),
        Space(),
        Word(value: 'Илия?'),
        Space(),
        Word(value: 'Он'),
        Space(),
        Word(value: 'сказал:'),
        Space(),
        Word(value: 'нет.'),
        Space(),
        Word(value: 'Пророк?'),
        Space(),
        Word(value: 'Он'),
        Space(),
        Word(value: 'отвечал:'),
        Space(),
        Word(value: 'нет.'),
        Space(),
        Word(value: '22'),
        Space(),
        Word(value: 'Сказали'),
        Space(),
        Word(value: 'ему:'),
        Space(),
        Word(value: 'кто'),
        Space(),
        Word(value: 'же'),
        Space(),
        Word(value: 'ты?'),
        Space(),
        Word(value: 'чтобы'),
        Space(),
        Word(value: 'нам'),
        Space(),
        Word(value: 'дать'),
        Space(),
        Word(value: 'ответ'),
        Space(),
        Word(value: 'пославшим'),
        Space(),
        Word(value: 'нас:'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'ты'),
        Space(),
        Word(value: 'скажешь'),
        Space(),
        Word(value: 'о'),
        Space(),
        Word(value: 'себе'),
        Space(),
        Word(value: 'самом?'),
        Space(),
        Word(value: '23'),
        Space(),
        Word(value: 'Он'),
        Space(),
        Word(value: 'сказал:'),
        Space(),
        Word(value: 'я'),
        Space(),
        Word(value: '«глас'),
        Space(),
        Word(value: 'вопиющего'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'пустыне:'),
        Space(),
        Word(value: 'исправьте'),
        Space(),
        Word(value: 'путь'),
        Space(),
        Word(value: 'Господу»,'),
        Space(),
        Word(value: ''),
        Space(),
        Word(value: 'как'),
        Space(),
        Word(value: 'сказал'),
        Space(),
        Word(value: 'пророк'),
        Space(),
        Word(value: 'Исаия.'),
        Space(),
        Word(value: '24'),
        Space(),
        Word(value: 'А'),
        Space(),
        Word(value: 'посланные'),
        Space(),
        Word(value: 'были'),
        Space(),
        Word(value: 'из'),
        Space(),
        Word(value: 'фарисеев;'),
        Space(),
        Word(value: '25'),
        Space(),
        Word(value: 'И'),
        Space(),
        Word(value: 'они'),
        Space(),
        Word(value: 'спросили'),
        Space(),
        Word(value: 'его:'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'же'),
        Space(),
        Word(value: 'ты'),
        Space(),
        Word(value: 'крестишь,'),
        Space(),
        Word(value: 'если'),
        Space(),
        Word(value: 'ты'),
        Space(),
        Word(value: 'ни'),
        Space(),
        Word(value: 'Христос,'),
        Space(),
        Word(value: 'ни'),
        Space(),
        Word(value: 'Илия,'),
        Space(),
        Word(value: 'ни'),
        Space(),
        Word(value: 'пророк?'),
        Space(),
        Word(value: '26'),
        Space(),
        Word(value: 'Иоанн'),
        Space(),
        Word(value: 'сказал'),
        Space(),
        Word(value: 'им'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'ответ:'),
        Space(),
        Word(value: 'я'),
        Space(),
        Word(value: 'крещу'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'воде;'),
        Space(),
        Word(value: 'но'),
        Space(),
        Word(value: 'стоит'),
        Space(),
        Word(value: 'среди'),
        Space(),
        Word(value: 'вас'),
        Space(),
        Word(value: 'Некто,'),
        Space(),
        Word(value: 'Которого'),
        Space(),
        Word(value: 'вы'),
        Space(),
        Word(value: 'не'),
        Space(),
        Word(value: 'знаете.'),
        Space(),
        Word(value: '27'),
        Space(),
        Word(value: 'Он-то'),
        Space(),
        Word(value: 'Идущий'),
        Space(),
        Word(value: 'за'),
        Space(),
        Word(value: 'мною,'),
        Space(),
        Word(value: 'но'),
        Space(),
        Word(value: 'Который'),
        Space(),
        Word(value: 'стал'),
        Space(),
        Word(value: 'впереди'),
        Space(),
        Word(value: 'меня.'),
        Space(),
        Word(value: 'Я'),
        Space(),
        Word(value: 'недостоин'),
        Space(),
        Word(value: 'развязать'),
        Space(),
        Word(value: 'ремень'),
        Space(),
        Word(value: 'у'),
        Space(),
        Word(value: 'обуви'),
        Space(),
        Word(value: 'Его.'),
        Space(),
        Word(value: '28'),
        Space(),
        Word(value: 'Это'),
        Space(),
        Word(value: 'происходило'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'Вифаваре'),
        Space(),
        Word(value: 'при'),
        Space(),
        Word(value: 'Иордане,'),
        Space(),
        Word(value: 'где'),
        Space(),
        Word(value: 'крестил'),
        Space(),
        Word(value: 'Иоанн.'),
        Space(),
        Word(value: '29'),
        Space(),
        Word(value: 'На'),
        Space(),
        Word(value: 'другой'),
        Space(),
        Word(value: 'день'),
        Space(),
        Word(value: 'видит'),
        Space(),
        Word(value: 'Иоанн'),
        Space(),
        Word(value: 'идущего'),
        Space(),
        Word(value: 'к'),
        Space(),
        Word(value: 'нему'),
        Space(),
        Word(value: 'Иисуса'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'говорит:'),
        Space(),
        Word(value: 'вот'),
        Space(),
        Word(value: 'Агнец'),
        Space(),
        Word(value: 'Божий,'),
        Space(),
        Word(value: 'Который'),
        Space(),
        Word(value: 'берет'),
        Space(),
        Word(value: 'на'),
        Space(),
        Word(value: 'Себя'),
        Space(),
        Word(value: 'грех'),
        Space(),
        Word(value: 'мира.'),
        Space(),
        Word(value: '30'),
        Space(),
        Word(value: 'Сей'),
        Space(),
        Word(value: 'есть,'),
        Space(),
        Word(value: 'о'),
        Space(),
        Word(value: 'Котором'),
        Space(),
        Word(value: 'я'),
        Space(),
        Word(value: 'сказал:'),
        Space(),
        Word(value: '«за'),
        Space(),
        Word(value: 'мною'),
        Space(),
        Word(value: 'идет'),
        Space(),
        Word(value: 'Муж,'),
        Space(),
        Word(value: 'Который'),
        Space(),
        Word(value: 'стал'),
        Space(),
        Word(value: 'впереди'),
        Space(),
        Word(value: 'меня,'),
        Space(),
        Word(value: 'потому'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'Он'),
        Space(),
        Word(value: 'был'),
        Space(),
        Word(value: 'прежде'),
        Space(),
        Word(value: 'меня».'),
        Space(),
        Word(value: '31'),
        Space(),
        Word(value: 'Я'),
        Space(),
        Word(value: 'не'),
        Space(),
        Word(value: 'знал'),
        Space(),
        Word(value: 'Его;'),
        Space(),
        Word(value: 'но'),
        Space(),
        Word(value: 'для'),
        Space(),
        Word(value: 'того'),
        Space(),
        Word(value: 'пришел'),
        Space(),
        Word(value: 'крестить'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'воде,'),
        Space(),
        Word(value: 'чтобы'),
        Space(),
        Word(value: 'Он'),
        Space(),
        Word(value: 'явлен'),
        Space(),
        Word(value: 'был'),
        Space(),
        Word(value: 'Израилю.'),
        Space(),
        Word(value: '32'),
        Space(),
        Word(value: 'И'),
        Space(),
        Word(value: 'свидетельствовал'),
        Space(),
        Word(value: 'Иоанн,'),
        Space(),
        Word(value: 'говоря:'),
        Space(),
        Word(value: 'я'),
        Space(),
        Word(value: 'видел'),
        Space(),
        Word(value: 'Духа,'),
        Space(),
        Word(value: 'сходящего'),
        Space(),
        Word(value: 'с'),
        Space(),
        Word(value: 'неба,'),
        Space(),
        Word(value: 'как'),
        Space(),
        Word(value: 'голубя,'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'пребывающего'),
        Space(),
        Word(value: 'на'),
        Space(),
        Word(value: 'Нем.'),
        Space(),
        Word(value: '33'),
        Space(),
        Word(value: 'Я'),
        Space(),
        Word(value: 'не'),
        Space(),
        Word(value: 'знал'),
        Space(),
        Word(value: 'Его;'),
        Space(),
        Word(value: 'но'),
        Space(),
        Word(value: 'Пославший'),
        Space(),
        Word(value: 'меня'),
        Space(),
        Word(value: 'крестить'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'воде'),
        Space(),
        Word(value: 'сказал'),
        Space(),
        Word(value: 'мне:'),
        Space(),
        Word(value: '«на'),
        Space(),
        Word(value: 'Кого'),
        Space(),
        Word(value: 'увидишь'),
        Space(),
        Word(value: 'Духа'),
        Space(),
        Word(value: 'сходящего'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'пребывающего'),
        Space(),
        Word(value: 'на'),
        Space(),
        Word(value: 'Нем,'),
        Space(),
        Word(value: 'Тот'),
        Space(),
        Word(value: 'есть'),
        Space(),
        Word(value: 'крестящий'),
        Space(),
        Word(value: 'Духом'),
        Space(),
        Word(value: 'Святым».'),
        Space(),
        Word(value: '34'),
        Space(),
        Word(value: 'И'),
        Space(),
        Word(value: 'я'),
        Space(),
        Word(value: 'видел'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'засвидетельствовал,'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'Сей'),
        Space(),
        Word(value: 'есть'),
        Space(),
        Word(value: 'Сын'),
        Space(),
        Word(value: 'Божий.'),
        Space(),
        Word(value: '35'),
        Space(),
        Word(value: 'На'),
        Space(),
        Word(value: 'другой'),
        Space(),
        Word(value: 'день'),
        Space(),
        Word(value: 'опять'),
        Space(),
        Word(value: 'стоял'),
        Space(),
        Word(value: 'Иоанн'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'двое'),
        Space(),
        Word(value: 'из'),
        Space(),
        Word(value: 'учеников'),
        Space(),
        Word(value: 'его.'),
        Space(),
        Word(value: '36'),
        Space(),
        Word(value: 'И,'),
        Space(),
        Word(value: 'увидев'),
        Space(),
        Word(value: 'идущего'),
        Space(),
        Word(value: 'Иисуса,'),
        Space(),
        Word(value: 'сказал:'),
        Space(),
        Word(value: 'вот'),
        Space(),
        Word(value: 'Агнец'),
        Space(),
        Word(value: 'Божий.'),
        Space(),
        Word(value: '37'),
        Space(),
        Word(value: 'Услышав'),
        Space(),
        Word(value: 'от'),
        Space(),
        Word(value: 'него'),
        Space(),
        Word(value: 'сии'),
        Space(),
        Word(value: 'слова,'),
        Space(),
        Word(value: 'оба'),
        Space(),
        Word(value: 'ученика'),
        Space(),
        Word(value: 'пошли'),
        Space(),
        Word(value: 'за'),
        Space(),
        Word(value: 'Иисусом.'),
        Space(),
        Word(value: '38'),
        Space(),
        Word(value: 'Иисус'),
        Space(),
        Word(value: 'же,'),
        Space(),
        Word(value: 'обратившись'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'увидев'),
        Space(),
        Word(value: 'их'),
        Space(),
        Word(value: 'идущих,'),
        Space(),
        Word(value: 'говорит'),
        Space(),
        Word(value: 'им:'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'вам'),
        Space(),
        Word(value: 'надобно?'),
        Space(),
        Word(value: 'Они'),
        Space(),
        Word(value: 'сказали'),
        Space(),
        Word(value: 'Ему:'),
        Space(),
        Word(value: 'Равви,'),
        Space(),
        Word(value: '—'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'значит:'),
        Space(),
        Word(value: '«учитель»,'),
        Space(),
        Word(value: '—'),
        Space(),
        Word(value: 'где'),
        Space(),
        Word(value: 'живешь?'),
        Space(),
        Word(value: '39'),
        Space(),
        Word(value: 'Говорит'),
        Space(),
        Word(value: 'им:'),
        Space(),
        Word(value: 'пойдите'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'увидите.'),
        Space(),
        Word(value: 'Они'),
        Space(),
        Word(value: 'пошли'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'увидели,'),
        Space(),
        Word(value: 'где'),
        Space(),
        Word(value: 'Он'),
        Space(),
        Word(value: 'живет;'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'пробыли'),
        Space(),
        Word(value: 'у'),
        Space(),
        Word(value: 'Него'),
        Space(),
        Word(value: 'день'),
        Space(),
        Word(value: 'тот.'),
        Space(),
        Word(value: 'Было'),
        Space(),
        Word(value: 'около'),
        Space(),
        Word(value: 'десятого'),
        Space(),
        Word(value: 'часа.'),
        Space(),
        Word(value: '40'),
        Space(),
        Word(value: 'Один'),
        Space(),
        Word(value: 'из'),
        Space(),
        Word(value: 'двух,'),
        Space(),
        Word(value: 'слышавших'),
        Space(),
        Word(value: 'от'),
        Space(),
        Word(value: 'Иоанна'),
        Space(),
        Word(value: 'об'),
        Space(),
        Word(value: 'Иисусе'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'последовавших'),
        Space(),
        Word(value: 'за'),
        Space(),
        Word(value: 'Ним,'),
        Space(),
        Word(value: 'был'),
        Space(),
        Word(value: 'Андрей,'),
        Space(),
        Word(value: 'брат'),
        Space(),
        Word(value: 'Симона'),
        Space(),
        Word(value: 'Петра.'),
        Space(),
        Word(value: '41'),
        Space(),
        Word(value: 'Он'),
        Space(),
        Word(value: 'первый'),
        Space(),
        Word(value: 'находит'),
        Space(),
        Word(value: 'брата'),
        Space(),
        Word(value: 'своего'),
        Space(),
        Word(value: 'Симона'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'говорит'),
        Space(),
        Word(value: 'ему:'),
        Space(),
        Word(value: 'мы'),
        Space(),
        Word(value: 'нашли'),
        Space(),
        Word(value: 'Мессию,'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'значит:'),
        Space(),
        Word(value: '«Христос».'),
        Space(),
        Word(value: '42'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'привел'),
        Space(),
        Word(value: 'его'),
        Space(),
        Word(value: 'к'),
        Space(),
        Word(value: 'Иисусу.'),
        Space(),
        Word(value: 'Иисус'),
        Space(),
        Word(value: 'же,'),
        Space(),
        Word(value: 'взглянув'),
        Space(),
        Word(value: 'на'),
        Space(),
        Word(value: 'него,'),
        Space(),
        Word(value: 'сказал:'),
        Space(),
        Word(value: 'ты'),
        Space(),
        Word(value: '—'),
        Space(),
        Word(value: 'Симон,'),
        Space(),
        Word(value: 'сын'),
        Space(),
        Word(value: 'Ионин;'),
        Space(),
        Word(value: 'ты'),
        Space(),
        Word(value: 'наречешься'),
        Space(),
        Word(value: 'Кифа,'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'значит:'),
        Space(),
        Word(value: '«камень»'),
        Space(),
        Word(value: '(Петр).'),
        Space(),
        Word(value: '43'),
        Space(),
        Word(value: 'На'),
        Space(),
        Word(value: 'другой'),
        Space(),
        Word(value: 'день'),
        Space(),
        Word(value: 'Иисус'),
        Space(),
        Word(value: ''),
        Space(),
        Word(value: 'восхотел'),
        Space(),
        Word(value: 'идти'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'Галилею,'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'находит'),
        Space(),
        Word(value: 'Филиппа'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'говорит'),
        Space(),
        Word(value: 'ему:'),
        Space(),
        Word(value: 'иди'),
        Space(),
        Word(value: 'за'),
        Space(),
        Word(value: 'Мною.'),
        Space(),
        Word(value: '44'),
        Space(),
        Word(value: 'Филипп'),
        Space(),
        Word(value: 'же'),
        Space(),
        Word(value: 'был'),
        Space(),
        Word(value: 'из'),
        Space(),
        Word(value: 'Вифсаиды,'),
        Space(),
        Word(value: 'из'),
        Space(),
        Word(value: 'одного'),
        Space(),
        Word(value: ''),
        Space(),
        Word(value: 'города'),
        Space(),
        Word(value: 'с'),
        Space(),
        Word(value: 'Андреем'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'Петром.'),
        Space(),
        Word(value: '45'),
        Space(),
        Word(value: 'Филипп'),
        Space(),
        Word(value: 'находит'),
        Space(),
        Word(value: 'Нафанаила'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'говорит'),
        Space(),
        Word(value: 'ему:'),
        Space(),
        Word(value: 'мы'),
        Space(),
        Word(value: 'нашли'),
        Space(),
        Word(value: 'Того,'),
        Space(),
        Word(value: 'о'),
        Space(),
        Word(value: 'Котором'),
        Space(),
        Word(value: 'писали'),
        Space(),
        Word(value: 'Моисей'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'законе'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'пророки,'),
        Space(),
        Word(value: 'Иисуса,'),
        Space(),
        Word(value: 'сына'),
        Space(),
        Word(value: 'Иосифова,'),
        Space(),
        Word(value: 'из'),
        Space(),
        Word(value: 'Назарета.'),
        Space(),
        Word(value: '46'),
        Space(),
        Word(value: 'Но'),
        Space(),
        Word(value: 'Нафанаил'),
        Space(),
        Word(value: 'сказал'),
        Space(),
        Word(value: 'ему:'),
        Space(),
        Word(value: 'из'),
        Space(),
        Word(value: 'Назарета'),
        Space(),
        Word(value: 'может'),
        Space(),
        Word(value: 'ли'),
        Space(),
        Word(value: 'быть'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'доброе?'),
        Space(),
        Word(value: 'Филипп'),
        Space(),
        Word(value: 'говорит'),
        Space(),
        Word(value: 'ему:'),
        Space(),
        Word(value: 'пойди'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'посмотри.'),
        Space(),
        Word(value: '47'),
        Space(),
        Word(value: 'Иисус,'),
        Space(),
        Word(value: 'увидев'),
        Space(),
        Word(value: 'идущего'),
        Space(),
        Word(value: 'к'),
        Space(),
        Word(value: 'Нему'),
        Space(),
        Word(value: 'Нафанаила,'),
        Space(),
        Word(value: 'говорит'),
        Space(),
        Word(value: 'о'),
        Space(),
        Word(value: 'нем:'),
        Space(),
        Word(value: 'вот'),
        Space(),
        Word(value: 'подлинно'),
        Space(),
        Word(value: 'Израильтянин,'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'котором'),
        Space(),
        Word(value: 'нет'),
        Space(),
        Word(value: 'лукавства.'),
        Space(),
        Word(value: '48'),
        Space(),
        Word(value: 'Нафанаил'),
        Space(),
        Word(value: 'говорит'),
        Space(),
        Word(value: 'Ему:'),
        Space(),
        Word(value: 'почему'),
        Space(),
        Word(value: 'Ты'),
        Space(),
        Word(value: 'знаешь'),
        Space(),
        Word(value: 'меня?'),
        Space(),
        Word(value: 'Иисус'),
        Space(),
        Word(value: 'сказал'),
        Space(),
        Word(value: 'ему'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'ответ:'),
        Space(),
        Word(value: 'прежде'),
        Space(),
        Word(value: 'нежели'),
        Space(),
        Word(value: 'позвал'),
        Space(),
        Word(value: 'тебя'),
        Space(),
        Word(value: 'Филипп,'),
        Space(),
        Word(value: 'когда'),
        Space(),
        Word(value: 'ты'),
        Space(),
        Word(value: 'был'),
        Space(),
        Word(value: 'под'),
        Space(),
        Word(value: 'смоковницею,'),
        Space(),
        Word(value: 'Я'),
        Space(),
        Word(value: 'видел'),
        Space(),
        Word(value: 'тебя.'),
        Space(),
        Word(value: '49'),
        Space(),
        Word(value: 'Нафанаил'),
        Space(),
        Word(value: 'отвечал'),
        Space(),
        Word(value: 'Ему:'),
        Space(),
        Word(value: 'Равви!'),
        Space(),
        Word(value: 'Ты'),
        Space(),
        Word(value: '—'),
        Space(),
        Word(value: 'Сын'),
        Space(),
        Word(value: 'Божий,'),
        Space(),
        Word(value: 'Ты'),
        Space(),
        Word(value: '—'),
        Space(),
        Word(value: 'Царь'),
        Space(),
        Word(value: 'Израилев.'),
        Space(),
        Word(value: '50'),
        Space(),
        Word(value: 'Иисус'),
        Space(),
        Word(value: 'сказал'),
        Space(),
        Word(value: 'ему'),
        Space(),
        Word(value: 'в'),
        Space(),
        Word(value: 'ответ:'),
        Space(),
        Word(value: 'ты'),
        Space(),
        Word(value: 'веришь,'),
        Space(),
        Word(value: 'потому'),
        Space(),
        Word(value: 'что'),
        Space(),
        Word(value: 'Я'),
        Space(),
        Word(value: 'тебе'),
        Space(),
        Word(value: 'сказал:'),
        Space(),
        Word(value: 'Я'),
        Space(),
        Word(value: 'видел'),
        Space(),
        Word(value: 'тебя'),
        Space(),
        Word(value: 'под'),
        Space(),
        Word(value: 'смоковницею;'),
        Space(),
        Word(value: 'увидишь'),
        Space(),
        Word(value: 'больше'),
        Space(),
        Word(value: 'сего.'),
        Space(),
        Word(value: '51'),
        Space(),
        Word(value: 'И'),
        Space(),
        Word(value: 'говорит'),
        Space(),
        Word(value: 'ему:'),
        Space(),
        Word(value: 'истинно,'),
        Space(),
        Word(value: 'истинно'),
        Space(),
        Word(value: 'говорю'),
        Space(),
        Word(value: 'вам:'),
        Space(),
        Word(value: 'отныне'),
        Space(),
        Word(value: 'будете'),
        Space(),
        Word(value: 'видеть'),
        Space(),
        Word(value: 'небо'),
        Space(),
        Word(value: 'отверстым'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'Ангелов'),
        Space(),
        Word(value: 'Божиих'),
        Space(),
        Word(value: 'восходящих'),
        Space(),
        Word(value: 'и'),
        Space(),
        Word(value: 'нисходящих'),
        Space(),
        Word(value: 'к'),
        Space(),
        Word(value: 'Сыну'),
        Space(),
        Word(value: 'Человеческому.'),
        Space(),
      ],
    );
  }
}
